<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
 <ItemGroup>
    <Compile Remove="backend.Tests/**/*.cs" />
    <EmbeddedResource Remove="backend.Tests/**/*.resx" />
    <None Remove="backend.Tests/**/*" />
  </ItemGroup>

</Project>
